
NUMBER_OF_POINTS_TRAJECTORY: 50  #set the number of point for the predicted trajectory ( >0 ! )

all_strategies:              #All the RGB and alpha(transparency) parameters for 
  current_pose_sphere:       #every markers, first identation for the wich stategy use this parameter
    r: 0.6                   #second identation name of the marker(same as topic name also)   
    g: 0.6                   #third indentation for RGB and alpha
    b: 0.6
    alpha: 0.1
  applied_ref_sphere:
    r: 0.6
    g: 0.6
    b: 0.6
    alpha: 0.1
  shortest_distance_lines:
    r: 0.0
    g: 0.0
    b: 0.0
    alpha: 1.0
  trajectory:
    r: 1.0
    g: 0.0
    b: 1.0
    alpha: 1.0
  line_between_current_positions:
    r: 1.0
    g: 0.0
    b: 0.0
    alpha: 1.0
  desired_ref_sphere:
    r: 0.6
    g: 0.6
    b: 0.6
    alpha: 0.1
  text_label:
    r: 0.
    g: 0.
    b: 0.
    alpha: 1.

strategy_1_tube:           #stategy 1 tube has one more identation, because RGBA parameter is not the same for every stategy
  strategy_1:
    cylinder_strategy_1:
      r: 0.4
      g: 0.698
      b: 1.0
      alpha: 0.075
  strategy_2_3_4:
    cylinder_strategy_1:
      r: 0.851
      g: 0.851
      b: 0.851
      alpha: 0.075

strategy_2_tube:
  cylinder_strategy_2:
    r: 0.4
    g: 0.698
    b: 1.0
    alpha: 0.075

strategy_3_tube:
  cylinder_strategy_3:
    r: 0.749
    g: 0.647
    b: 0.412
    alpha: 0.25

strategy_4_tube:
  cylinder_strategy_4:
    r: 0.749
    g: 0.647
    b: 0.412
    alpha: 0.25
  hemisphere1_strategy_4:
    r: 0.8
    g: 0.0
    b: 0.0
    alpha: 0.25
  hemisphere2_strategy_4:
    r: 0.8
    g: 0.0
    b: 0.0
    alpha: 0.25

strategy_0:
  error_sphere:
    r: 0.8
    g: 0.898
    b: 1.0
    alpha: 0.1

trajectory:                  #radius, diameter and width for trajectory markers and line markers
  spheres:
    radius: 0.05
  arrow:
    shaft_diameter: 0.075 
    head_diameter: 0.125
  line:
    width: 0.025
current_position_line:
  width: 0.05
shortest_ditance_line:
  width: 0.05

text_label_size: 0.5       

